name: MSBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - ProjectFile: projects/burgerv10win.sln
          - ProjectFile: projects/burgerv10x36.sln
          - ProjectFile: projects/burgerv12win.sln
          - ProjectFile: projects/burgerv13win.sln
          - ProjectFile: projects/burgerv15ps3.sln
          - ProjectFile: projects/burgerv15shi.sln
          - ProjectFile: projects/burgerv15vit.sln
          - ProjectFile: projects/burgerv15win.sln
          - ProjectFile: projects/burgerv19win10.sln
          - ProjectFile: projects/burgerv22and.sln
          - ProjectFile: projects/burgerv22sta.sln
          - ProjectFile: projects/burgerv22win10.sln
          - ProjectFile: projects/burgervc7w32.sln
          - ProjectFile: projects/burgervc8win.sln
          - ProjectFile: projects/burgervc9win.sln

    steps:
    - uses: actions/checkout@v4
      with:
        repository: Olde-Skuul/burgerlib
        submodules: true

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{matrix.ProjectFile}}
