name: MSBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - ProjectFile: burgerv10win.sln
          - ProjectFile: burgerv10x36.sln
          - ProjectFile: burgerv12win.sln
          - ProjectFile: burgerv13win.sln
          - ProjectFile: burgerv15ps3.sln
          - ProjectFile: burgerv15shi.sln
          - ProjectFile: burgerv15vit.sln
          - ProjectFile: burgerv15win.sln
          - ProjectFile: burgerv19win10.sln
          - ProjectFile: burgerv22and.sln
          - ProjectFile: burgerv22sta.sln
          - ProjectFile: burgerv22win10.sln
          - ProjectFile: burgervc7w32.sln
          - ProjectFile: burgervc8win.sln
          - ProjectFile: burgervc9win.sln

    steps:
    - uses: actions/checkout@v4
      with:
        repository: Olde-Skuul/burgerlib
        submodules: true

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}} /p:ProjectFile=${{matrix.ProjectFile}}
